### ISSUE TITLE
How does a distribution opt in to static installation?

### ISSUE THREAD

**Issue by mauke** [Perl-Toolchain-Gang/cpan-static#12] opened 2023-04-29 08:24 UTC
The spec talks mostly about what cpan clients should do to install distributions statically, but how do I as an author specify that my distribution supports static installation?

**Comment by Leont** [comment] 2023-04-29 10:02
This is essentially a duplicate of #6

**Closed as completed by Leont** 2023-04-29 10:02 UTC

**Comment by mauke** [comment] 2023-04-30 09:12
Fixed in https://github.com/Perl-Toolchain-Gang/cpan-static/commit/478aa5d9ab71f8c6578d888773b412e287e0e37c.
